import type { Metadata } from "next";
import { Lobster, Raleway } from "next/font/google";
import "./globals.css";

const lobster = Lobster({
  weight: ["400"],
  subsets: ["latin-ext"],
  variable: "--font-lobster",
});
const roboto = Raleway({
  weight: ["400", "100", "300"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "PATI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lobster.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
